language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - pytest test/
after_success:
  - bash <(curl -s https://codecov.io/bash) -t c18f2a5b-6240-4bec-a551-b427163f05b8
